[bastion]
13.245.136.136 ansible_user=ec2-user ansible_ssh_private_key_file=./ansible/.ssh ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[app]
10.0.2.178 ansible_user=ec2-user ansible_ssh_private_key_file=./ansible/.ssh ansible_ssh_common_args='-o ProxyCommand="ssh -i ./ansible/.ssh -W %h:%p -o StrictHostKeyChecking=no ec2-user@13.245.136.136" -o StrictHostKeyChecking=no'
