# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI workflow

on:
  push:
    branches: ["devbranch"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint code
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Docker image
        run: docker build -t learn2grow-backend .
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'learn2grow-backend' # Must match the tag from your build step
          format: 'table'
          exit-code: '1' # This is crucial! It fails the step if issues are found.
          ignore-unfixed: true
          severity: 'CRITICAL' # Fail only for Critical issues

  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint code
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Docker image
        run: docker build -t frontend-app .
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend-app' 
          format: 'table'
          exit-code: '1' 
          ignore-unfixed: true
          severity: 'CRITICAL' 

  scan-infrastructure:
    name: Scan Terraform Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan Terraform code
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/ 
          # exit_code: 1 # Fail the step if issues are found
          # severity: 'CRITICAL' # Fail only for Critical issues
