# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npx eslint . --ext .ts,.tsx

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t learn2grow-backend .

  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: docker build -t frontend-app .
